@extends('layouts.admin')

@section('content')
<div class="flex flex-col">
    <div class="mb-6 flex justify-between items-center">
        <div>
            <h1 class="text-3xl font-bold text-gray-800">Gestionar Disponibilidad</h1>
            <p class="text-gray-600">Configura horarios especiales por día.</p>
        </div>
    </div>

    <!-- Main Content Wrapper -->
    <div class="flex flex-col md:flex-row flex-1 bg-white rounded-lg shadow min-h-[600px]">
        <!-- Calendar Sidebar -->
        <div class="w-full md:w-1/3 border-r bg-gray-50 p-6 flex flex-col items-center">
            <h3 class="font-bold text-gray-700 mb-4 self-start">Selecciona una Fecha</h3>
            <!-- Calendar Container: Removed p-2, Changed ID -->
            <div id="availability-calendar" class="bg-white rounded-lg shadow mb-6 mx-auto"></div>
            
            <div class="w-full">
                <h4 class="font-bold text-gray-700 mb-3 border-b pb-1">Días Personalizados</h4>
                <div class="space-y-2">
                    @forelse($availabilities as $av)
                        @php $date = \Carbon\Carbon::parse($av->date); @endphp
                        <button onclick="jumpToDate('{{ $date->format('Y-m-d') }}')" class="w-full text-left bg-white p-3 rounded-lg border hover:border-pink-500 hover:shadow-sm transition flex justify-between items-center group">
                            <div>
                                <span class="font-bold text-gray-800 text-sm block">{{ $date->locale('es')->isoFormat('D MMM YYYY') }}</span>
                                <span class="text-xs text-gray-500 truncate max-w-[150px] block">{{ $av->message ?: 'Horario especial' }}</span>
                            </div>
                            <svg class="w-4 h-4 text-gray-300 group-hover:text-pink-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                        </button>
                    @empty
                        <p class="text-xs text-gray-400 text-center py-2">No configuraciones.</p>
                    @endforelse
                </div>
            </div>
        </div>

        <!-- Slot Manager -->
        <div class="w-full md:w-2/3 p-6 flex flex-col min-h-[600px]">
            <div id="editor-panel" class="hidden flex flex-col">
                <div class="mb-4 pb-4 border-b flex-shrink-0">
                    <h2 class="text-xl font-bold text-gray-800">Editando: <span id="selected-date-display" class="text-pink-600 capitalize"></span></h2>
                    <p class="text-sm text-gray-500">Selecciona las horas disponibles para este día.</p>
                </div>

                <div class="mb-4 flex-shrink-0">
                    <label class="block text-gray-700 font-bold mb-1">Mensaje para el Cliente (Opcional)</label>
                    <input type="text" id="day-message" class="w-full border rounded-lg px-4 py-2 focus:ring-2 focus:ring-pink-500" placeholder="Ej: Solo turno tarde...">
                </div>

                <div class="flex-grow flex flex-col">
                    <div class="flex justify-between items-end mb-2 flex-shrink-0">
                        <label class="block text-gray-700 font-bold">Franjas Horarias</label>
                        <div class="text-xs space-x-2">
                            <span class="inline-block w-4 h-4 bg-gray-200 rounded align-middle border"></span> Cerrado
                            <span class="inline-block w-4 h-4 bg-green-500 rounded align-middle border border-green-600"></span> Abierto
                        </div>
                    </div>
                    
                    <div id="slots-grid-container" class="border rounded-lg bg-gray-50 p-4">
                        <div id="slots-grid" class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-3">
                            <!-- Slots generated by JS -->
                        </div>
                    </div>
                    <div class="mt-8 flex gap-4 border-t pt-6 bg-white flex-shrink-0">
                    <button onclick="saveAvailability()" class="flex-1 bg-pink-600 text-white font-bold py-3 rounded-lg hover:bg-pink-700 transition shadow-md flex justify-center items-center gap-2">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
                        Guardar Horarios
                    </button>
                    <button onclick="clearDay()" class="px-6 py-3 border border-red-300 text-red-600 rounded-lg hover:bg-red-50 font-semibold transition" title="Restablecer">
                        Restablecer
                    </button>
                </div>
                </div>

                
            </div>

            <div id="empty-state" class="flex flex-col items-center justify-center text-gray-400 py-20">
                <svg class="w-16 h-16 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                <p>Selecciona una fecha para configurar.</p>
            </div>
        </div>
    </div> <!-- End Wrapper -->
</div> <!-- End Main Container -->
    
@push('styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/airbnb.css">
<style>
    .slot-btn { transition: all 0.2s; }
    .slot-btn.active { background-color: #ec4899; color: white; border-color: #db2777; box-shadow: 0 2px 4px rgba(236, 72, 153, 0.3); transform: scale(1.05); }
    .slot-btn.inactive { background-color: #f3f4f6; color: #9ca3af; border-color: #e5e7eb; }
    .slot-btn.inactive:hover { background-color: #e5e7eb; }
    
    /* Configured dates marker in calendar */
    .flatpickr-day.has-config {
        border-bottom-color: #ec4899;
        font-weight: bold;
    }
    .flatpickr-day.has-config:after {
        content: '';
        position: absolute;
        bottom: 2px;
        left: 50%;
        transform: translateX(-50%);
        width: 4px;
        height: 4px;
        background-color: #ec4899;
        border-radius: 50%;
    }
    
    /* Calendar customizations to match pink theme */
    .flatpickr-calendar {
        box-shadow: none !important;
        border: none !important;
        width: 100% !important; /* Make it fill container */
        max-width: 320px; /* Limit max width */
        margin: 0 auto;
    }
    .flatpickr-months .flatpickr-month {
        background: #fff;
        color: #374151;
        fill: #374151;
    }
    .flatpickr-current-month .flatpickr-monthDropdown-months {
        font-weight: 700;
    }
    .flatpickr-day.selected, .flatpickr-day.startRange, .flatpickr-day.endRange, .flatpickr-day.selected.inRange, .flatpickr-day.startRange.inRange, .flatpickr-day.endRange.inRange, .flatpickr-day.selected:focus, .flatpickr-day.startRange:focus, .flatpickr-day.endRange:focus, .flatpickr-day.selected:hover, .flatpickr-day.startRange:hover, .flatpickr-day.endRange:hover, .flatpickr-day.selected.prevMonthDay, .flatpickr-day.startRange.prevMonthDay, .flatpickr-day.endRange.prevMonthDay, .flatpickr-day.selected.nextMonthDay, .flatpickr-day.startRange.nextMonthDay, .flatpickr-day.endRange.nextMonthDay {
        background: #ec4899;
        border-color: #ec4899;
    }
    .flatpickr-day.today {
        border-color: #ec4899;
    }
    .flatpickr-day:hover {
        background: #fdf2f8;
        border-color: #fce7f3;
    }
</style>
@endpush

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    let selectedDate = null;
    let activeSlots = new Set();
    let fpInstance = null;
    const defaultHoursStart = 8;
    const defaultHoursEnd = 21; 
    
    // Dates with config to mark in calendar
    const configuredDates = @json($availabilities->pluck('date')->map(fn($d)=> \Carbon\Carbon::parse($d)->format('Y-m-d')));

    document.addEventListener('DOMContentLoaded', function() {
        if (typeof flatpickr === 'undefined') {
            console.error('Flatpickr library not loaded');
            Swal.fire('Error', 'Librería de calendario no cargada. Intenta recargar.', 'error');
            return;
        }

        fpInstance = flatpickr("#availability-calendar", {
            inline: true,
            locale: "es",
            dateFormat: "Y-m-d", // Force format
            disableMobile: true,
            onDayCreate: function(dObj, dStr, fp, dayElem) {
                // Correctly format JS date object to Y-m-d using local time
                const date = dayElem.dateObj;
                const offset = date.getTimezoneOffset();
                const localDate = new Date(date.getTime() - (offset*60*1000));
                const isoDate = localDate.toISOString().split('T')[0];
                
                if (configuredDates.includes(isoDate)) {
                    dayElem.classList.add('has-config');
                }
            },
            onChange: function(selectedDates, dateStr) {
                if (!dateStr) return;
                loadDate(dateStr);
            }
        });
    });

    function jumpToDate(dateStr) {
        if(fpInstance) {
            fpInstance.setDate(dateStr, false);
            loadDate(dateStr);
        }
    }

    function generateAllSlots() {
        const slots = [];
        for (let h = defaultHoursStart; h <= defaultHoursEnd; h++) {
            slots.push(`${h.toString().padStart(2, '0')}:00`);
            slots.push(`${h.toString().padStart(2, '0')}:30`);
        }
        return slots;
    }

    async function loadDate(dateStr) {
        selectedDate = dateStr;
        const [y, m, d] = dateStr.split('-');
        const dateObj = new Date(y, m-1, d);
        document.getElementById('selected-date-display').innerText = dateObj.toLocaleDateString('es-CO', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
        
        document.getElementById('empty-state').classList.add('hidden');
        document.getElementById('editor-panel').classList.remove('hidden');
        document.getElementById('editor-panel').scrollIntoView({ behavior: 'smooth', block: 'start' });
        document.getElementById('slots-grid').innerHTML = '<p class="col-span-full text-center py-10">Cargando...</p>';
        document.getElementById('day-message').value = '';

        try {
            const resp = await fetch(`{{ route('admin.availability.show') }}?date=${dateStr}`);
            const data = await resp.json();
            
            renderGrid(data.exists ? data.active_slots : null); 
            if (data.message) document.getElementById('day-message').value = data.message;
            
        } catch (e) {
            console.error(e);
            Swal.fire('Error', 'No se pudo cargar la configuración', 'error');
        }
    }

    function renderGrid(savedSlots) {
        const grid = document.getElementById('slots-grid');
        grid.innerHTML = '';
        activeSlots.clear();

        const allSlots = generateAllSlots();
        const isDefault = (savedSlots === null);
        
        allSlots.forEach(time => {
            const btn = document.createElement('button');
            btn.className = "slot-btn py-2 rounded font-bold text-sm border";
            btn.setAttribute('translate', 'no'); // Prevent translation
            btn.innerText = formatTo12h(time);
            
            let isActive = false;
            if (isDefault) {
                isActive = true; 
            } else {
                isActive = savedSlots.includes(time);
            }

            if (isActive) {
                btn.classList.add('active');
                activeSlots.add(time);
            } else {
                btn.classList.add('inactive');
            }

            btn.onclick = () => toggleSlot(btn, time);
            grid.appendChild(btn);
        });
    }

    function toggleSlot(btn, time) {
        if (activeSlots.has(time)) {
            activeSlots.delete(time);
            btn.classList.remove('active');
            btn.classList.add('inactive');
        } else {
            activeSlots.add(time);
            btn.classList.remove('inactive');
            btn.classList.add('active');
        }
    }

    async function saveAvailability() {
        if (!selectedDate) {
            Swal.fire('Atención', 'Selecciona una fecha primero', 'warning');
            return;
        }

        try {
            Swal.fire({title: 'Guardando...', didOpen: () => Swal.showLoading()});
            
            const resp = await fetch(`{{ route('admin.availability.store') }}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                },
                body: JSON.stringify({
                    date: selectedDate,
                    active_slots: Array.from(activeSlots).sort(),
                    message: document.getElementById('day-message').value
                })
            });

            if (resp.ok) {
                Swal.fire({
                    icon: 'success',
                    title: 'Guardado',
                    text: 'La disponibilidad se ha actualizado.',
                    timer: 1500,
                    showConfirmButton: false
                }).then(() => location.reload()); // Reload to update list
            } else {
                const errorData = await resp.json();
                const errorMessage = errorData.message || 'Error desconocido';
                // Check for validation errors
                let detailedErrors = '';
                if(errorData.errors) {
                    detailedErrors = Object.values(errorData.errors).flat().join('<br>');
                }
                throw new Error(detailedErrors || errorMessage);
            }
        } catch (e) {
            Swal.fire({
                icon: 'error',
                title: 'Error',
                html: `No se pudo guardar: <br>${e.message}`,
                confirmButtonColor: '#ec4899'
            });
        }
    }

    function clearDay() {
        if (!selectedDate) return;
        
        Swal.fire({
            title: '¿Restablecer horario?',
            text: "Se eliminará la configuración personalizada para este día y volverá al horario normal.",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Sí, restablecer'
        }).then((result) => {
            if (result.isConfirmed) {
                deleteAvailability();
            }
        });
    }

    async function deleteAvailability() {
        try {
            Swal.fire({title: 'Restableciendo...', didOpen: () => Swal.showLoading()});
            
            const resp = await fetch(`{{ route('admin.availability.destroy') }}?date=${selectedDate}`, {
                method: 'DELETE',
                headers: {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                }
            });

            if (resp.ok) {
                Swal.fire(
                    'Restablecido',
                    'El día ha vuelto a su horario normal.',
                    'success'
                ).then(() => location.reload());
            } else {
                throw new Error('Error al eliminar');
            }
        } catch (e) {
            Swal.fire('Error', 'No se pudo restablecer el día', 'error');
        }
    }

    function formatTo12h(timeStr) {
        if (!timeStr) return '';
        const [h, m] = timeStr.split(':');
        let hh = parseInt(h);
        const ampm = hh >= 12 ? ' PM' : ' AM';
        hh = hh % 12;
        if (hh === 0) hh = 12;
        return `${hh}:${m}${ampm}`;
    }
</script>
@endpush
@endsection
